<?php 
/*
 * STEM Playground Options List
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Register Options
return array(
    'title' => __( 'STEM Playground Options Panel', UPTOWNCODE_PLUGIN_NAME ),
    'logo'  => UPTOWNCODE_PLUGIN_URL . 'assets/img/STEMPlayground-logo.png',
    'menus' => array(
		array(
			'title' => __( 'General', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'general',
			'icon' => 'font-awesome:fa-gear',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'at_risk_threshold',
					'label' => __('At-Risk Threshold', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the threshold for the percentage of teachers that must mark a school as at-risk for it to be considered at-risk.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '80',
				),
				array(
					'type' => 'slider',
					'name' => 'ell_threshold',
					'label' => __('ESL Threshold', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the threshold for the percentage of students in a class to be marked ELL for the class to be considered ELL.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '50',
				),
				array(
					'type' => 'slider',
					'name' => 'school_ell_threshold',
					'label' => __('School ESL Threshold', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the threshold for the percentage of classes in a school considered ELL for the school to be considered ELL.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '50',
				),
				array(
					'type' => 'select',
					'name' => 'school_year_month',
					'label' => __( 'School Year Cutoff Month', UPTOWNCODE_PLUGIN_NAME ),
					'description' => __('This sets the cutoff month for the school year.', UPTOWNCODE_PLUGIN_NAME),
					'items' => array(
						'data' => array(
							array(
								'source' => 'function',
								'value' => 'get_uc_months',
							),
					    ),
					),
				),
				array(
					'type' => 'slider',
					'name' => 'school_year_day',
					'label' => __('School Year Cutoff Day', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the cutoff day for the school year.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '31',
					'step' => '1',
					'default' => '15',
				),
				array(
					'type' => 'slider',
					'name' => 'school_year_first_year',
					'label' => __('School Year First Year', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('First year this software should look for.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '2012',
					'max' => '2018',
					'step' => '1',
					'default' => '2013',
				),
			)
		),
		array(
			'title' => __( 'Challenges and Awards', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'challenges',
			'icon' => 'font-awesome:fa-star',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'ch_min_classes',
					'label' => __('Minimum Classes competing for top 10%', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the minimum number of classes needed to compete in a demographic to hand out Class Awards. Setting this to 0 removes the limit.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '20',
					'step' => '1',
					'default' => '10',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_post_id',
					'label' => __( 'League Challenge Link Post ID', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Board. In this field, include the Post ID of the page that the text "Whats the League Challenge?" will link to', UPTOWNCODE_PLUGIN_NAME ),
					'default' => '',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_act_brd_text',
					'label' => __( 'Activity Board League Challenge Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Text on Activity Board for League Challenges. The text "!activities!" will be replaced with the number of Activities left.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You have !activities! League Challenge Activities Left',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_act_brd_single_text',
					'label' => __( 'Activity Board League Challenge Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Text on Activity Board for League Challenges when one activity is left.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You have 1 League Challenge Activity Left',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_act_brd_zero_text',
					'label' => __( 'Activity Board League Challenge Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Text on Activity Board for League Challenges when all activities are completed.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You have completed all of the League Challenge Activities',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_act_brd_x_text',
					'label' => __( 'Activity Board League Challenge Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Text on Activity Board for League Challenges when at least one of the League Challenge Activities have expired.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You are ineligible for the League Challenge',
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_act_brd_link',
					'label' => __( 'League Challenge Link Post ID', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Link text on Activity Board for League Challenges.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => "What's the League Challenge?",
				),
				array(
					'type' => 'textbox',
					'name' => 'ch_view_results_text',
					'label' => __( 'League Challenge View Results Link Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Link text on Activity Board for viewing League Challenge results.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => "View your League Challenge results",
				),
				array(
					'type' => 'select',
					'name' => 'a_award_year_month',
					'label' => __( 'Award Distribution Month', UPTOWNCODE_PLUGIN_NAME ),
					'description' => __('This sets the month for class and team award distributions.', UPTOWNCODE_PLUGIN_NAME),
					'items' => array(
						'data' => array(
							array(
								'source' => 'function',
								'value' => 'get_uc_months',
							),
					    ),
					),
				),
				array(
					'type' => 'slider',
					'name' => 'a_award_year_day',
					'label' => __('Award Distribution Day', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the day for class and team award distributions', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '31',
					'step' => '1',
					'default' => '15',
				),
			),
		),
		array(
			'title' => __( 'Signups', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'signups',
			'icon' => 'font-awesome:fa-refresh',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'signup_maximum',
					'label' => __('Maximum Signups', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('Maximum number of concurrent active signups a class may have at a time. Setting this to zero gives no limit.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '10',
					'step' => '1',
					'default' => '2',
				),
			),
		),
		array(
			'title' => __( 'Activities', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'activities',
			'icon' => 'font-awesome:fa-sticky-note-o',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'activity_expiration_length',
					'label' => __('Activity Length', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('The amount of days available to complete an activity before it expires.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '30',
				),
				array(
					'type' => 'slider',
					'name' => 'teamwork_1',
					'label' => __('(%) Teamwork Score 1 Multiplier', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '0',
				),
				array(
					'type' => 'slider',
					'name' => 'teamwork_2',
					'label' => __('(%) Teamwork Score 2 Multiplier', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '2',
				),
				array(
					'type' => 'slider',
					'name' => 'teamwork_3',
					'label' => __('(%) Teamwork Score 3 Multiplier', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '10',
				),
				array(
					'type' => 'slider',
					'name' => 'teamwork_4',
					'label' => __('(%) Teamwork Score 4 Multiplier', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '20',
				),
				array(
					'type' => 'slider',
					'name' => 'teamwork_5',
					'label' => __('(%) Teamwork Score 5 Multiplier', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '50',
				),
				array(
					'type' => 'slider',
					'name' => 'max_teamwork_5',
					'label' => __('(%) Maximum Teamwork 5 Scores', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '100',
					'step' => '1',
					'default' => '20',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_a_board_max_signup',
					'label' => __( 'Activity Board Max Signup Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Board above Available Activities when teacher is signed up for the maximum active activities. The text "!signups!" will be replaced with the max number of signups.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You are signed up for !signups! activities.  Please complete and upload results for one before signing up for another.',
				),
				array(
					'type' => 'textarea',
					'name' => 'a_available_text',
					'label' => __( 'Activity Available Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if Activity is available. The text "!days!" will be replaced with the Activity Length variable.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your class can sign up for this activity. Please note that, once signed up, you have !days! days to complete the activity.',
				),
				array(
					'type' => 'textarea',
					'name' => 'a_active_text',
					'label' => __( 'Activity Active Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if Activity is active. The text "!days!" will be replaced with the Activity Length variable.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your class is currently enrolled in this activity.',
				),
				array(
					'type' => 'textarea',
					'name' => 'a_complete_text',
					'label' => __( 'Activity Complete Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if Activity is available. The text "!days!" will be replaced with the Activity Length variable.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your class has completed this activity. Below are their results.',
				),
				array(
					'type' => 'textarea',
					'name' => 'a_max_text',
					'label' => __( 'Max Activities Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if Activity is unavailable due to max signups. The text "!signups!" will be replaced with the max number of signups.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Only !signups! activites may be active at a time. Please complete other activities.',
				),
				array(
					'type' => 'textarea',
					'name' => 'a_expired_text',
					'label' => __( 'Activity Expired Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if Activity is available. The text "!days!" will be replaced with the Activity Length variable.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'This activity has expired.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_missing_scores',
					'label' => __( 'Activity Missing Scores Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if scores are missing.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please fill out valid scores for all active groups before submitting.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_teamwork_5',
					'label' => __( 'Activity Teamwork 5 Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if the percentage of Teamwork 5 bonuses are above the threshold.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please reduce the number of Teamwork Score 5 bonuses.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_min_error',
					'label' => __( 'Activity Score Below Min Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if the submitted score is below the min. The text "!name!" and "!score!" will be replaced with the score name and the min score, respectively.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a !name! score of !score! or above.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_max_error',
					'label' => __( 'Activity Score Above Max Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if the submitted score is above the max. The text "!name!" and "!score!" will be replaced with the score name and the max score, respectively.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a !name! score of !score! or below.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_changed_teams',
					'label' => __( 'Activity Changed Teams Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page if teams are changed before submitting score data.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please save teams before submitting scores.',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_class_chart_title',
					'label' => __( 'Chart Title', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page for results. The text "!grade!" will be replaced with the class grade, and the text !activitytitle! will be replaced with the activity title.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => '!grade! Grade Class Average for !activitytitle!',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_class_chart_subtitle',
					'label' => __( 'Chart Subtitle', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page for results.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'TBD',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_team_chart_title',
					'label' => __( 'Chart Title', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page for results. The text "!grade!" will be replaced with the class grade, and the text !activitytitle! will be replaced with the activity title.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => '!grade! Grade Team Average for !activitytitle!',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_team_chart_subtitle',
					'label' => __( 'Chart Subtitle', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Activity Page for results.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'TBD',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_activity_board_text',
					'label' => __( 'Link to Activity Board', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Button displayed on Activity Page.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Back to Activity Board',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_activity_page_problems_text',
					'label' => __( 'Activity Page Problems Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Text displayed on Activity Page. The text "!email!" will be replaced with the email', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Any problems? Email us at !email!',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_activity_page_problems_email',
					'label' => __( 'Activity Page Problems Email Address', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email displayed on Activity Page.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'support@stemplayground.org',
				),
				array(
					'type' => 'textbox',
					'name' => 'a_activity_page_signup_link',
					'label' => __( 'Activity Page Signup Link', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Link text displayed on Activity Page for not logged in users.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Sign up for STEM Playground here!',
				),
			),
		),
		array(
			'title' => __( 'Teams', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'teams',
			'icon' => 'font-awesome:fa-users',
			'controls' => array(
				array(
					'type' => 'textarea',
					'name' => 'default_group_text',
					'label' => __( 'Default Team Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on the Default Team page above the groups.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Drag each student to a group.',
				),
				array(
					'type' => 'slider',
					'name' => 'group_size',
					'label' => __('Team Size', UPTOWNCODE_PLUGIN_NAME),
					'description'	=> __('Size of groups. If the class size is not divisible by this number, additional students may be placed in teams of one larger size.', UPTOWNCODE_PLUGIN_NAME ),
					'min' => '1',
					'max' => '10',
					'step' => '1',
					'default' => '2',
				),
				array(
					'type' => 'textbox',
					'name' => 'group_missing_student_error',
					'label' => __( 'Missing students error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed after Team update due to not having all students assigned to teams. This occurs only for default teams.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please place all students in groups before saving.',
				),
				array(
					'type' => 'textbox',
					'name' => 'group_size_error',
					'label' => __( 'Team size error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed after Team update due to having invalid team sizes. The text "!teamsize!" will be replaced with the team size, and "!teamsize+1!" will be replaced with the team size plus 1.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'All teams must have !teamsize!-!teamsize+1! students.',
				),
				array(
					'type' => 'textbox',
					'name' => 'group_proceed',
					'label' => __( 'Proceed to Activities text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed after first successful team save as a link to Activities page.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Proceed to the Activity Board',
				),
			),
		),
		array(
			'title' => __( 'Students', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'students',
			'icon' => 'font-awesome:fa-child',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'st_max_students',
					'label' => __('Students Maximum', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the maximum number of students a class may have. Setting this to zero allows for unlimited students per class', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '50',
					'step' => '1',
					'default' => '30',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_min_banner',
					'label' => __( 'Student Minimum Banner Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Students page warning the user that they have not yet met the minimum', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Minimum number of students not met!',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_ell_question',
					'label' => __( 'ESL Question', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page for the ESL question', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Is this student learning English as a second language (ESL)?',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_verify_errors',
					'label' => __( 'Student Verified Errors', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Students page due to multiple errors. The text "!fields!" will be replaced with the number of field errors.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed !fields! fields. They have been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_verify_error',
					'label' => __( 'Student Verified Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to a single error.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed 1 field. It has been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_stfirstname_req',
					'label' => __( 'Zipcode Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Student page due to not filling in first name.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a first name',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_stlastinitial_req',
					'label' => __( 'Last Initial Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Student page due to not filling in last initial.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a last initial',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_stlastinitial_min_max',
					'label' => __( 'Last Initial Min Max Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to last initial not being 1 character.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Last initial must be one character',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_stgrade_req',
					'label' => __( 'Grade Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Student page due to not choosing grade.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please choose a grade',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_stgender_req',
					'label' => __( 'Gender Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Student page due to not choosing gender.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please choose a gender',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_stell_req',
					'label' => __( 'ELL Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Student page due to not choosing ell.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please choose a ELL property',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_max_students_text',
					'label' => __( 'Student Maxiumum Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Students page due to having too many students. The text "!students!" will be replaced with the Students Maximum variable.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your class has too many students. Only !students! students are allowed per class.',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_remove_warning',
					'label' => __( 'Student Remove Warning', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Students page before removing student.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Are you sure you want to do this? This action cannot be reversed.',
				),
				array(
					'type' => 'textbox',
					'name' => 'st_proceed',
					'label' => __( 'Proceed to Teams text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed after first successful student add as a link to Teams page.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'When you have completed adding your students, proceed to edit teams',
				),
			),
		),
		array(
			'title' => __( 'Classes', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'classes',
			'icon' => 'font-awesome:fa-graduation-cap',
			'controls' => array(
				array(
					'type' => 'slider',
					'name' => 'class_maximum',
					'label' => __('Class Maximum', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the maximum number of classes a teacher may have. Setting this to zero allows for unlimited classes', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '10',
					'step' => '1',
					'default' => '4',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_max_error',
					'label' => __( 'Max Classes Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page due to having the maximum number of classes. The text "!maximum!" will be replaced with the class maximum', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You may only have !maximum! classes.',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_no_name_error',
					'label' => __( 'No Name Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page due to no name being filled out.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please fill out a valid name for your class.',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_same_name_error',
					'label' => __( 'Same Name Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page due to having the same name as an existing class.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You may not name your class the same as a previous class of yours.',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_verify_various',
					'label' => __( 'Verify Various Text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page due to teacher selecting Various as class grade', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'By selecting your class grade as various, you acknowledge that your class will only be compared with other classes with multiple grade levels.',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_remove_warning',
					'label' => __( 'Class Remove Warning', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Classes page before removing class.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Are you sure you want to do this? This action cannot be reversed.',
				),
				array(
					'type' => 'textbox',
					'name' => 'class_proceed',
					'label' => __( 'Proceed to Students text', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed after first successful class add as a link to Students page.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Proceed to edit students',
				),
			),
		),
		array(
			'title' => __( 'Schools', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'schools',
			'icon' => 'font-awesome:fa-home',
			'controls' => array(
				array(
					'type' => 'textbox',
					'name' => 'sc_what_country',
					'label' => __( 'School What Country', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page above country dropdown', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'What country is your school in?',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_search_intro',
					'label' => __( 'School Search Intro', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page above zip code search.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Enter the zip code of your school.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_search_results',
					'label' => __( 'School Search Results', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on results success of School Search. The text "!number!" will be replaced with the number of schools found.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Found !number! schools.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_search_result',
					'label' => __( 'School Search Results', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on single result success of School Search.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Found 1 school.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_search_result_0',
					'label' => __( 'School Search Zero Reults', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on no results success of School Search.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Found no schools.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_non_trad_q',
					'label' => __( 'School Non Traditional Question', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page for non-traditional question', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Is your school non-traditional?',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_verify_errors',
					'label' => __( 'User Verified Errors', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to multiple errors. The text "!fields!" will be replaced with the number of field errors.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed !fields! fields. They have been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_verify_error',
					'label' => __( 'User Verified Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to a single error.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed 1 field. It has been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sctitle_req',
					'label' => __( 'School Name Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in school name.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a school name',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_scaddress1_req',
					'label' => __( 'Address1 Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in address1.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a street address',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sccity_req',
					'label' => __( 'City Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in city.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a city',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sccounty_req',
					'label' => __( 'County Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in county.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a county',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_scstate_req',
					'label' => __( 'State Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in state.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please choose a state',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sczip_req',
					'label' => __( 'Zipcode Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in zipcode.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a zipcode',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sczip_min_max',
					'label' => __( 'Zipcode Min Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to zipcode being less than 5 characters.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a valid zip code',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_sccountry_req',
					'label' => __( 'Country Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School page due to not filling in country.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please choose a country',
				),
				array(
					'type' => 'textbox',
					'name' => 'sc_submit_error',
					'label' => __( 'School Submit Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on School Page when the school was not created successfully, due to incorrectly submitted data or address validation issues.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your school was not submitted. Please enter your information again. If you continue to have problems, email us at XXXX',
				),
			),
		),
		array(
			'title' => __( 'Teachers', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'teachers',
			'icon' => 'font-awesome:fa-black-tie',
			'controls' => array(
			),
		),
		array(
			'title' => __( 'Users', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'users',
			'icon' => 'font-awesome:fa-user',
			'controls' => array(
				array(
					'type' => 'textbox',
					'name' => 'notify_question',
					'label' => __( 'Notify Question', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page for Notify question.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Would you like to identify anyone to notify of your registration?',
				),
				array(
					'type' => 'slider',
					'name' => 'notify_max',
					'label' => __('Maximum Notifications', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('This sets the maximum number of notifications. Setting this to zero will allow unlimited notifications', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '10',
					'step' => '1',
					'default' => '0',
				),
				array(
					'type' => 'textbox',
					'name' => 'convertkit_question',
					'label' => __( 'Convertkit Question', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page for Convertkit question.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Would you like to sign up for our mailing list?',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_stem_question',
					'label' => __( 'STEM Major Question', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page for STEM major question.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Do you have a college STEM major?',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_verify_error',
					'label' => __( 'User Verified Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to a single error.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed 1 field. It has been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_verify_errors',
					'label' => __( 'User Verified Errors', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to multiple errors. The text "!fields!" will be replaced with the number of field errors.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'You missed !fields! fields. They have been highlighted.',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_uname_req',
					'label' => __( 'Username Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to not filling in username.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a username',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_uname_taken',
					'label' => __( 'Username Taken Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to username being taken.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your username has already been taken.',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_uname_min',
					'label' => __( 'Username Minimum Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to username being less than 6 characters.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your username must consist of at least 6 characters',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_upass_req',
					'label' => __( 'Password Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to not filling in password.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a password',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_upass_min',
					'label' => __( 'Password Minimum Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to password being less than 6 characters.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your password must consist of at least 6 characters',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_upass_equal',
					'label' => __( 'Password Not Equal Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to password confirmation not matching.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your passwords must match',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_ufirst_req',
					'label' => __( 'First Name Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to not filling in first name.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a first name',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_ulast_req',
					'label' => __( 'Last Name Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to not filling in last name.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a last name',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_uemail_req',
					'label' => __( 'Email Required Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to not filling in email.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter an email address',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_uemail_email',
					'label' => __( 'Email Invalid Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Sign Up page due to email not being a valid email.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please enter a valid email address',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_confirm_email_subj',
					'label' => __( 'User Confirmation Email Subject', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email confirmation email subject, sent after signup. The texts "!firstname!", "!lastname!" will be replaced.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Please confirm your email',
				),
				array(
					'type' => 'textbox',
					'name' => 'us_submit_error',
					'label' => __( 'User Submit Error', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Displayed on Signup Page when the signup was not created successfully, due to incorrectly submitted or duplicated data.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'There was an error creating your account. Please verify your information again and try submitting again. If you continue to have problems, email us at XXXX',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'us_confirm_email',
					'label' => __( 'User Confirmation Email Body', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email confirmation email, sent after signup. The texts "!firstname!", "!lastname!" will be replaced.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => '!firstname!, please confirm your email address to secure your STEM Playground account.',
				),
			),
		),
		array(
			'title' => __( 'Sponsors', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'sponsors',
			'icon' => 'font-awesome:fa-money',
			'controls' => array(
				array(
					'type' => 'textbox',
					'name' => 'sponsor_price',
					'label' => __( 'Price of Sponsorship', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Price is in cents. For example, 1099 for $10.99', UPTOWNCODE_PLUGIN_NAME ),
					'default' => '1099',
				),
				array(
					'type' => 'textbox',
					'name' => 'sponsor_email_subj',
					'label' => __( 'Sponsorship Email Subject', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Sponsorship email, sent after filling the sponsorship form out. The texts "!name!", "!classname!", "!teachername!" will be replaced.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Your Sponsorship Receipt',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'sponsor_email_body',
					'label' => __( 'Sponsorship Email Body', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Sponsorship email, sent after signup. The texts "!name!", "!classname!", "!teachername!" will be replaced.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Thanks, !name!, for becoming a sponsor for !teachername!\'s class, !classname!.',
				),
			),
		),
		array(
			'title' => __( 'Emails', UPTOWNCODE_PLUGIN_NAME ),
			'name' => 'emails',
			'icon' => 'font-awesome:fa-envelope',
			'controls' => array(
				array(
					'type' => 'notebox',
					'name' => 'nb_1',
					'label' => __( 'Note', UPTOWNCODE_PLUGIN_NAME ),
					'description' => __( 'All emails in this section will replace !first_name!, !last_name!, and !user_email!, in addition to other noted replacements.', UPTOWNCODE_PLUGIN_NAME ),
					'status' => 'normal',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_missing_class',
					'label' => __( 'Missing Class Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent 3 days after user registers, if they are missing their class.', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_missing_class',
					'label' => __( 'Missing Class Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_missing_students',
					'label' => __( 'Missing Students Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent 3 days after user registers, if they are missing their students. Replacement codes: !class_name!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_missing_students',
					'label' => __( 'Missing Students Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_missing_teams',
					'label' => __( 'Missing Teams Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent 3 days after user registers, if they are missing their teams. Replacement codes: !class_name!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_missing_teams',
					'label' => __( 'Missing Teams Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_admin_notify',
					'label' => __( 'User wants to share SP Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to administrators or other teachers when the user wants to share SP. Replacement codes: !notify_email!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_admin_notify',
					'label' => __( 'User wants to share SP Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_no_activity_30',
					'label' => __( '30 Day No Activity Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when a class has not enrolled in an activity for 30 days. Replacement codes: !class_name!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_no_activity_30',
					'label' => __( '30 Day No Activity Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'slider',
					'name' => 'days_no_activity_30',
					'label' => __('30 Day No Activity Days', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('Manually change the # of days for the 30 Day No Activity email.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '60',
					'step' => '1',
					'default' => '30',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_no_activity_60',
					'label' => __( '60 Day No Activity Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when a class has not enrolled in an activity for 60 days. Replacement codes: !class_name!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_no_activity_60',
					'label' => __( '60 Day No Activity Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'slider',
					'name' => 'days_no_activity_60',
					'label' => __('60 Day No Activity Days', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('Manually change the # of days for the 60 Day No Activity email.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '120',
					'step' => '1',
					'default' => '60',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_no_activity_90',
					'label' => __( '90 Day No Activity Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when a class has not enrolled in an activity for 90 days. Replacement codes: !class_name!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_no_activity_90',
					'label' => __( '90 Day No Activity Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'slider',
					'name' => 'days_no_activity_90',
					'label' => __('90 Day No Activity Days', UPTOWNCODE_PLUGIN_NAME),
					'description' => __('Manually change the # of days for the 90 Day No Activity email.', UPTOWNCODE_PLUGIN_NAME),
					'min' => '0',
					'max' => '180',
					'step' => '1',
					'default' => '90',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_enroll_receipt',
					'label' => __( 'Enrollment Receipt Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when the teacher has enrolled a class in an activity. Replacement codes: !class_name!, !activity_name!, !materials_required!, !activity_expire_date!, !signup_date!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_enroll_receipt',
					'label' => __( 'Enrollment Receipt Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_expire_7_days',
					'label' => __( '7 Days Until Expiration Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when their signup expires in 7 days. Replacement codes: !class_name!, !activity_name!, !materials_required!, !activity_expire_date!, !signup_date!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_expire_7_days',
					'label' => __( '7 Days Until Expiration Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_expire_1_day',
					'label' => __( '1 Day Until Expiration Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to teachers when their signup expires in 1 day. Replacement codes: !class_name!, !activity_name!, !materials_required!, !activity_expire_date!, !signup_date!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_expire_1_day',
					'label' => __( '1 Day Until Expiration Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'wpeditor',
					'name' => 'email_upload_receipt',
					'label' => __( 'Upload Receipt Email', UPTOWNCODE_PLUGIN_NAME ),
					'description'	=> __('Email sent to users when activity results are uploaded. Replacement codes: !activity_name! !results_link!, !activity_board_link!', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
				array(
					'type' => 'textbox',
					'name' => 'subj_upload_receipt',
					'label' => __( 'Upload Receipt Subject', UPTOWNCODE_PLUGIN_NAME ),
					'default' => 'Aaaaaaaaaa',
				),
			),
		),
    ),
);

 ?>